# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bd362a518de280e6d165c26005c8eae50b8734eb0bb7c8d01aedbc78d8d95fef3937c2014c5723c7bcbc4a42eddc3cfbe30c05e58aa8be382514eb3141ebff8

test:
  secret_key_base: e33cf88de2bdcecde17d44ff302e43387e89c845ae17dccac8287aa88917be7ef2f42264547d1a7a02c07531bc664d8d8e26652cf4c4ff92e408fbb79ea75704

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
